"""Generate .trivyignore from policies/license/dependency-risk-exceptions.json.

Keeps Trivy CVE exceptions in sync with the canonical pip-audit exception registry.
Each non-expired exception is written as:

    # <owner>: <reason>
    CVE-YYYY-NNNNN exp:<expires>

The `exp:` suffix (Trivy v0.37+) lets Trivy auto-expire the entry on the given date,
mirroring the same expiry discipline enforced by run_pip_audit_with_policy.py.
"""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXCEPTIONS_FILE = ROOT / "policies" / "license" / "dependency-risk-exceptions.json"
TRIVYIGNORE_FILE = ROOT / ".trivyignore"

_HEADER = """\
# Auto-generated by scripts/generate_trivyignore.py
# Source of truth: policies/license/dependency-risk-exceptions.json
# Do NOT edit manually — changes will be overwritten in CI.
"""


def generate_trivyignore(exceptions_file: Path = EXCEPTIONS_FILE) -> str:
    data = json.loads(exceptions_file.read_text(encoding="utf-8"))
    today = date.today()
    expired: list[str] = []
    blocks: list[str] = []

    for exc in data.get("exceptions", []):
        cve_id = exc.get("id", "")
        try:
            expires = date.fromisoformat(exc["expires"])
        except (KeyError, ValueError):
            expired.append(f"{cve_id}: missing or invalid expires field")
            continue
        if expires < today:
            expired.append(f"{cve_id} (package: {exc.get('package', '?')}, expired: {exc['expires']})")
            continue
        owner = exc.get("owner", "unknown")
        reason = exc.get("reason", "")
        blocks.append(f"# {owner}: {reason}\n{cve_id} exp:{exc['expires']}")

    if expired:
        raise SystemExit(
            "Expired CVE exceptions block .trivyignore generation:\n- " + "\n- ".join(expired)
        )

    sections = [_HEADER] + blocks
    return "\n".join(sections) + ("\n" if blocks else "")


def main() -> None:
    content = generate_trivyignore()
    TRIVYIGNORE_FILE.write_text(content, encoding="utf-8")
    exception_count = content.count("exp:")
    print(f".trivyignore written: {exception_count} active exception(s)")


if __name__ == "__main__":
    main()
